---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes

- name: Install required packages
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    state: present

- name: Install Docker
  ansible.builtin.apt:
    name: docker.io
    state: present

- name: Start and enable Docker service
  ansible.builtin.service:
    name: docker
    state: started
    enabled: yes

- name: Pull SonarQube image
  community.docker.docker_image:
    name: sonarqube
    tag: lts
    source: pull

- name: Run SonarQube container
  community.docker.docker_container:
    name: sonarqube
    image: sonarqube:lts
    state: started
    restart_policy: always
    published_ports:
      - "9000:9000"