---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes

- name: Install required packages
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    state: present

- name: Install Docker
  ansible.builtin.apt:
    name: docker.io
    state: present

- name: Start and enable Docker service
  ansible.builtin.service:
    name: docker
    state: started
    enabled: yes

- name: Pull SonarQube image
  community.docker.docker_image:
    name: sonarqube
    tag: lts
    source: pull

- name: Run SonarQube container
  community.docker.docker_container:
    name: sonarqube
    image: sonarqube:lts
    state: started
    restart_policy: always
    published_ports:
      - "9000:9000"

- name: Create Jenkins home directory
  ansible.builtin.file:
    path: /opt/jenkins_home
    state: directory
    owner: 1000
    group: 1000
    mode: '0755'

- name: Pull Jenkins Docker image
  community.docker.docker_image:
    name: jenkins/jenkins
    tag: lts
    source: pull

- name: Run Jenkins container
  community.docker.docker_container:
    name: jenkins
    image: jenkins/jenkins:lts
    state: started
    restart_policy: always
    published_ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - /opt/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

- name: Wait for Jenkins to initialize
  ansible.builtin.wait_for:
    path: /opt/jenkins_home/secrets/initialAdminPassword
    timeout: 60

- name: Get Jenkins initial admin password
  ansible.builtin.command: docker exec jenkins cat /var/jenkins_home/secrets/initialAdminPassword
  register: jenkins_password
  changed_when: false

- name: Show Jenkins initial admin password
  ansible.builtin.debug:
    msg: "Jenkins initial admin password is: {{ jenkins_password.stdout }}"
